# Numpy

O numpy é uma poderosa bibliotéca amplamente utilizada para cálculos multidimencionais com Arrays, além de oferecer um grande conjuntos de operações e manipulações dessas Arrays ela bem rápida nos seus cálculos.

In [2]:
import numpy as np

## Lista ou Array unidimencionais

In [2]:
# Criando uma lista
lista = np.array([1,2,3,4,5]);
print(lista)

# Adicionando um elemento na lista
lista = np.append(lista,[6])
print(lista)

# Removendo um elemento da lista
# Lembrando que é informado a posição do elemento na lista
# que será deletado
lista = np.delete(lista,0) 
print(lista)


[1 2 3 4 5]
[1 2 3 4 5 6]
[2 3 4 5 6]


### Operações Aritméticas com Listas

In [3]:
l1 = np.array([1,2,3,4,5])
print(l1)

# as 3 Operações Básicas (+ , -,*)
l1 += 2; print(l1)
l1 -= 3; print(l1)
l1 *= 2; print(l1)

l2 = np.array([9,7,6,5,4]) 

l3 = l1 + l2; print(l3)
l3 = l1 - l2; print(l3)
l3 = l1 * l2; print(l3)

# Divisão
# Para divisão é preciso que o tipo da lista seja Flaot ou Double
# https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html
l1 = np.array([1,2,3,4,5], dtype='float64');print(l1)
l1 /= 2; print(l3)
l3 = l1 / l2; print(l3)

[1 2 3 4 5]
[3 4 5 6 7]
[0 1 2 3 4]
[0 2 4 6 8]
[ 9  9 10 11 12]
[-9 -5 -2  1  4]
[ 0 14 24 30 32]
[1. 2. 3. 4. 5.]
[ 0 14 24 30 32]
[0.05555556 0.14285714 0.25       0.4        0.625     ]


In [4]:
# Potência
lista = np.array([1,2,3,4,5])
lista = lista ** 2
print(lista)
lista **=3
print(lista)

# MOD
mod = lista % 2
print(mod)

# Raiz
raiz_quadrada = np.sqrt(lista)
print(raiz_quadrada)

# Log 
ln = np.log(lista) #Base ln
print(ln)
log10 =  np.log10(lista) #Base 10
print(log10)
log2 =  np.log2(lista) #Base 2
print(log2)
log1p =  np.log1p(lista) # == np.log(1+ ELEMENT)
print(log1p)

lista = np.array([1,2,3,4,5])
exp = np.exp(lista) #e^x
print(exp)

[ 1  4  9 16 25]
[    1    64   729  4096 15625]
[1 0 1 0 1]
[  1.   8.  27.  64. 125.]
[0.         4.15888308 6.59167373 8.31776617 9.65662747]
[0.         1.80617997 2.86272753 3.61235995 4.19382003]
[ 0.          6.          9.509775   12.         13.93156857]
[0.69314718 4.17438727 6.59304453 8.31801028 9.65669147]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


### Dot Product - Produto do ponto
O produto do ponto para arrays unidimencionais e nada mais que o produto interno entre 2 vetores.
$$ a \bullet b = |a||b|cos\theta_{ab}$$

In [5]:
a = np.array([1,2])
b = np.array([2,1])

dot = 0

# Calculando o produto do ponto sem numpy
for e,f in zip(a,b):
    dot += e*f
    
print(dot)

# Calculando o produto do ponto com numpy
print(np.sum(a*b))
print((a*b).sum())
print(np.dot(a,b))
print(a.dot(b), b.dot(a))


4
4
4
4
4 4


## Magnetude de um vetor

A magnetude de um vetor é a distância entre dois ponto e este calculo se dá por:

$$ |AB| = \sqrt{x^2 + y^2}$$


In [6]:
a = np.array([1,2])
b = np.array([2,1])

magnetude_a = np.sqrt((a*a).sum())
print(magnetude_a)

magnetude_a = np.linalg.norm(a)
print(magnetude_a)


2.23606797749979
2.23606797749979


### Cálculo do Ângulo

In [7]:
a = np.array([1,2])
b = np.array([2,1])

cos_angulo = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

angulo = np.arccos(cos_angulo)
print(angulo) # por padrão vem em Radianos

0.6435011087932847
